### ISSUE TITLE
ValueError: Table sites_site does not exist

### ISSUE THREAD

**Issue by boolow5** [boolow5/3wm-challenge#3]
```
python manage.py loaddata sites.json
Traceback (most recent call last):
  File "/Users/bolow/Projects/3wm-challenge/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/bolow/Projects/3wm-challenge/venv/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 303, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: sites_site

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/bolow/Projects/3wm-challenge/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/Users/bolow/Projects/3wm-challenge/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/bolow/Projects/3wm-challenge/venv/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/bolow/Projects/3wm-challenge/venv/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/Users/bolow/Projects/3wm-challenge/venv/lib/python3.6/site-packages/django/core/management/commands/loaddata.py", line 72, in handle
    self.loaddata(fixture_labels)
  File "/Users/bolow/Projects/3wm-challenge/venv/lib/python3.6/site-packages/django/core/management/commands/loaddata.py", line 113, in loaddata
    self.load_label(fixture_label)
  File "/Users/bolow/Projects/3wm-challenge/venv/lib/python3.6/site-packages/django/core/management/commands/loaddata.py", line 177, in load_label
    obj.save(using=self.using)
  File "/Users/bolow/Projects/3wm-challenge/venv/lib/python3.6/site-packages/django/core/serializers/base.py", line 205, in save
    models.Model.save_base(self.object, using=using, raw=True, **kwargs)
  File "/Users/bolow/Projects/3wm-challenge/venv/lib/python3.6/site-packages/django/db/models/base.py", line 759, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/bolow/Projects/3wm-challenge/venv/lib/python3.6/site-packages/django/db/models/base.py", line 823, in _save_table
    forced_update)
  File "/Users/bolow/Projects/3wm-challenge/venv/lib/python3.6/site-packages/django/db/models/base.py", line 872, in _do_update
    return filtered._update(values) > 0
  File "/Users/bolow/Projects/3wm-challenge/venv/lib/python3.6/site-packages/django/db/models/query.py", line 709, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/Users/bolow/Projects/3wm-challenge/venv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1379, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/Users/bolow/Projects/3wm-challenge/venv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1068, in execute_sql
    cursor.execute(sql, params)
  File "/Users/bolow/Projects/3wm-challenge/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/Users/bolow/Projects/3wm-challenge/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/bolow/Projects/3wm-challenge/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/bolow/Projects/3wm-challenge/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/bolow/Projects/3wm-challenge/venv/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/bolow/Projects/3wm-challenge/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/bolow/Projects/3wm-challenge/venv/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 303, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: Problem installing fixture '/Users/bolow/Projects/3wm-challenge/sitesproject/sites.json': Could not load sites.Site(pk=1): no such table: sites_site
```

**Comment by boolow5** [comment]
If you encounter this it means the `sites` app is not migrated.

```bash
python manage.py makemigrations sites
python manage.py migrate sites
```
